### PR TITLE
have a AZs become parameterized [#171196475]

### PR DESCRIPTION
**Pull request by kcboyle**
Signed-off-by: Kira Boyle <kboyle@pivotal.io>
Co-authored-by: Kira Boyle <kboyle@pivotal.io>

### CODE REVIEW

**Comment by cirocosta** [comment]
Hey @kcboyle ,

Thanks for the PR!

Please correct me if I'm wrong, but I think we'd need to update [./cluster/README.md](./cluster/README.md) to include the default `z1` availability zone as part of the set of environment variables for a seamless deployment - is that right?

Thanks!

**Comment by cirocosta** [comment]
(oh, one more question: what's `[#171196475]` about? 🤔)

**Comment by jtarchie** [comment]
Some teams at Pivotal use a tool call Pivotal Tracker for story and product management. :trollface:

**Comment by making** [comment]
Hi, this commit is a breaking change and can make existing users who use default az value unhappy. 
How about providing the following ops file instead?

```yaml
- type: replace
  path: /instance_groups/name=web/azs
  value: ((availability_zones))

- type: replace
  path: /instance_groups/name=db/azs
  value: ((availability_zones))

- type: replace
  path: /instance_groups/name=worker/azs
  value: ((availability_zones))
```

**Comment by jtarchie** [comment]
We've discussed with @cirocosta, that we will update the `README.md`, so the `bosh deploy` command has `-v availability_zones="[z1]"` in the example.

For example, arrays can be passed via `-v` (or vars files):

```
→ echo "azs: ((azs))" | bosh int - -v azs="[z1]"
azs:
- z1

Succeeded
```

This won't _break_ deployments as the `bosh deploy` will fail fast on the missing value.

**Comment by making** [comment]
> This won't break deployments as the bosh deploy will fail fast on the missing value.

OK. I was thinking this was a breaking change.
I'm aware that some users have a script (`deploy-concourse.sh`) and they usually update concourse by `cd concourse-bosh-deployment (submodule)  && git pull origin master && cd .. && ./deploy-concourse.sh`
I just worried the users will be surprised to see deploy fails because of the lack of variables.

**Comment by jtarchie** [comment]
@making, we are working on different definitions of failures for deployment here.
When I say, "deployed failed", it is because the deployment went through and a VM didn't come up.
This `bosh deploy` command will fail because a variable is missing.
I don't consider that a _failure_, just an update to the configuration.

**Comment by making** [comment]
@jtarchie Thanks for the clarification.

**Comment by jtarchie** [comment]
I am renaming this from `availability_zones` to `azs` so it is similarly named like [`external-worker.yml`](https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/external-worker.yml#L17)

**Pull request merged**
