### PR TITLE
Add http-proxy.yml

### PR DESCRIPTION
**Pull request by making**
in order to install concourse behind HTTP proxy ...

### CODE REVIEW

**Comment by vito** [comment]
Makes sense. One question though: is setting the properties on Garden necessary? They should only be needed for `rootfs_uri:` in a task, which has been deprecated/discouraged for years.

If we don't have to set those, configuring this will be a bit easier, since then you only need one form of `no_proxy`.

**Comment by making** [comment]
Thank you for your comment!

I was thinking that the properties on Garden is necessary.
After checking it works without these for sure, I'll update this PR.

**Comment by making** [comment]
Confirmed `garden` was not required and updated PR

**Comment by vito** [comment]
Thanks!

**Pull request merged**
