### PR TITLE
ensure postgres connections are secure between UAA, Credhub, and Conc…

### LINKED ISSUE #202: uaa requires the disabling of postgres TLS to be used correctly
We had to add custom ops file for UAA to be able to connect to the same postgres instance that is allocated for Concourse via `cluster`.

```yaml
- type: replace
  path: /instance_groups/name=web/jobs/name=uaa/properties/uaadb?/tls
  value: disabled
```

Options:
1. Fix UAA ops file so it uses TLS.
2. Always disable it.

### PR DESCRIPTION
**Pull request by iplay88keys**
…ourse web

Closes #202

Signed-off-by: JT Archie <jarchie@pivotal.io>
Co-authored-by: JT Archie <jarchie@pivotal.io>

### CODE REVIEW

**Review by cirocosta — COMMENTED** [review]
Hey, 

the changes seem very sensible, and indeed valuable! thanks!

I'm curious about BBR though - are these changes compatible with the current BBR setup?

thanks!

**Comment by jtarchie** [comment]
We are going to update the PR to have opsfiles for securing the internal postgres which will affect the colocated jobs of UAA, Credhub, and BBR.

**Comment by iplay88keys** [comment]
@cirocosta We manually tested a secured Concourse deployment with BBR deployed with the appropriate TLS certs/keys. We had no issues backing up or restoring.

**Comment by cirocosta** [comment]
hey @matthewpereira, it'd probably be a good idea to have these ops files recommended as default (so that folks get "secure by default")

**Pull request merged**
