### PR TITLE
Adding ops file to set the garden-runc docker_registry_endpoint.

### PR DESCRIPTION
**Pull request by rob-greene**

### CODE REVIEW

**Comment by vito** [comment]
I'm not sure if this will do what you want. Similar to https://github.com/concourse/concourse-bosh-deployment/pull/52 - people *really* shouldn't be using `rootfs_uri` for their tasks, which is the only thing this would affect.

**Comment by rob-greene** [comment]
Not sure what to note except the garden spec: https://github.com/cloudfoundry/garden-runc-release/blob/9e0cc0070826be08a59d05d67f4a07143df2a338/jobs/garden/spec#L55

We are behind a proxy which will block Docker images unless we are pulling them from our internal repository. This particular configuration does happen to set the Garden `config.ini` to contain `docker-registry = ["internal-url"]` as expected.

**Comment by vito** [comment]
@rob-greene Right, but that property only affects Garden's Docker image fetching flow, which really shouldn't be what you're using with Concourse. That's only exercised by `rootfs_uri`, which we don't encourage.

You should probably be configuring the Docker Image resource instead: https://github.com/concourse/docker-image-resource

Can you confirm whether you're using (and/or need to use) `rootfs_uri`?

**Comment by rob-greene** [comment]
Not that I'm aware of.  I see nothing in the ops files and nothing in the pipelines that were loaded. Most of the pipelines are either directly from our vendor or based on pipelines from our vendor.  (I have all the source in a workspace - both Bosh as well as pipelines - and simply did a search against `rootfs_uri`.)

Is there a broader setting in Concourse to set the Docker registry or does it need to be done task by task in each pipeline?

Thanks!

**Comment by vito** [comment]
@rob-greene Yeah, it needs to be set by each task - it's part of the `repository` string, and should be the same value you'd set in a `FROM` line in a `Dockerfile`.

I'm gonna close this out since it sounds like it wouldn't end up helping anyway. Thanks though!

**Pull request closed without merging**
