### PR TITLE
Update basic-auth.yml

### PR DESCRIPTION
**Pull request by siennathesane**
Fixes bug related to #80.

### CODE REVIEW

**Comment by vito** [comment]
What bug does this fix? 2-level vars should work fine. That's how CredHub works. :thinking:

**Comment by siennathesane** [comment]
With the period, this error occurs:

```
  - Unable to render jobs for instance group 'web'. Errors are:
    - Unable to render templates for job 'web'. Errors are:
      - Failed to find variable '/bosh/concourse-staging/local_user' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'
```

The same issue occurred in #80.

**Comment by vito** [comment]
That's not a bug, the var just isn't present in the config server and hasn't been provided statically. Have you tried specifying `--var local_user.username=foo`?

**Comment by siennathesane** [comment]
Providing the variable statically is not a viable option as this environment pulls all variables from config server as part of a system requirement.

**Comment by vito** [comment]
@mxplusb Don't you just need to set `local_user` as a variable in the config server then? The current usage expects a CredHub 'user' type variable. See https://docs.cloudfoundry.org/credhub/credential-types.html#cred-types

**Comment by vito** [comment]
Guess I'll close this, but let me know if it was still a problem and I can reopen!

**Pull request closed without merging**
