### PR TITLE
Added UAA and CredHub ops files and more

### PR DESCRIPTION
**Pull request by brightzheng100**
A bundle of changes made:
1. Updated cluster/concourse.yml: made azs configurable;
2. Updated versions.yml: added uua, credhub info
3. Added cluster/concourse-params.yml: used as example and simplified the command line
4. Updated cluster/operations/basic-auth.yml: added corresponding variables
5. Added cluster/operations/static-db.yml: added ops file for static db ip
6. Updated cluster/operations/tls.yml: added corresponding variables
7. Added cluster/operations/uaa.yml: added ops file for UAA
8. Added cluster/operations/credhub.yml: added ops file for CredHub
9. Updated cluster/README.md: updated with more info while using more ops files

### CODE REVIEW

**Comment by sethlindberg** [comment]
Complete outside here with a question - I know when setting up a bosh director with credhub, the order of operations files is important (uaa.yml first, then credhub.yml) - here it's reversed.  Is credhub first, then uaa important, or is the order unimportant here?

**Comment by brightzheng100** [comment]
Different stories and this really depends on how we define the roles of these components.
You may have a look at the ops files and I believe you can find that there might be dependent by one to another.

**Comment by vito** [comment]
There are a lot of unrelated changes in here which is gonna make this take a long time to review. (I was scared away by how big it was and am only just now able to get to it...)

Could you please make this PR a bit smaller, perhaps by submitting smaller, more focused ones with only the necessary changes? There's a lot of unnecessary renaming/reorganizing of all the YAML which is gonna make `git blame` annoying to sift through, plus a bunch of other changes snuck in (e.g. https://github.com/concourse/concourse-bosh-deployment/pull/54/commits/b4d187eed5754ef9dd2bcad89199ba3ebb1e6512#diff-23170bda1e960c5279ebaeca97776fa3R18).

Thanks for taking the time to submit this, though. I just don't have time to review it as-is. Sorry for the delay!

**Comment by z4ce** [comment]
@brightzheng100 I hope you submit these as smaller PRs. They would definitely be useful operators!

**Comment by brightzheng100** [comment]
@vito @z4ce looks too ambitious maybe:)
As all these came from a real DOJO engagement and I thought each of them was reasonable for making a change.
Will try to break them down to smaller PRs as what you requested, if time allows, so that the team is easier to review and approve.

**Comment by brightzheng100** [comment]
@vito @z4c, now please refer to #68 for a smaller PR for UAA + CredHub integration

**Pull request closed without merging**
