### PR TITLE
Adds an ops file for those using BBL lbs

### PR DESCRIPTION
**Pull request by evanfarrar**
Hello fellow aeronauts!

We maintain instructions in the bosh-bootloader repo for an easy way to install BOSH+concourse with the load balancers created by bbl:
https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/concourse.md

It would be even simpler if they could run this without editing any files, and just use some file in this repo. I'm open to a different name for the file (like "external-lbs.yml"), or a different name for the load balancer (like "concourse-web"), but we forward port 80 and we use a VM extension to add loadbalancers to IaaS agnostic VM types and those are opinions we like.

### CODE REVIEW

**Comment by cppforlife** [comment]
last line is extra.

**Comment by vito** [comment]
Isn't this equivalent to just using the `privileged-http` and `web-network-extensions` ops files?

**Comment by evanfarrar** [comment]
`privileged-http` seems fine to me and I could drop the port 80 stuff from this PR. 

As for `web-network-extension`, the extension name is an additional undefined value you have to come up with a value for. The name of that extension is decoupled from something meaningful to users like the IaaS identifier for the load balancer, so they aren't expressing a preference when they bind that value, it is just named what it happens to be named. They could have named it something different in their cloud config if they knew in advance what to name it.

I'd be cool with `web-network-extension` if it were hardcoded to something or if there were a default (web-network-properties is the convention CF uses, but do what you want). If this happened, bbl could create a VM extension with that name, and a load balancer with that name, and a meaningful name can translate across all three levels of abstraction.

In the glorious future, BOSH will create load balancers and this relationship will be the total reverse of what you have now: the name of the vm-extension (or similar YAML entity) that is used in the deployment manifest will create a meaningfully named load balancer in the IaaS if it does not already exist.

**Comment by vito** [comment]
Ya lost me.

All I'm saying is this is exactly equivalent to:

```sh
-o operations/privileged-http.yml \
-o operations/web-network-extensions.yml \
-v web_network_vm_extension=lb
```

...so it'd be confusing to have another ops file in the mix that does the same thing. Won't people just be copy-pasting a command either way?

I'm not seeing where having a hard-coded value in `web-network-extensions.yml` really helps things either. How does that enable BBL to do anything different? Does it not respect `-v` or something? Hard-coding it would break things for people that have a different extension name (like us).

**Comment by vito** [comment]
Closing due to inactivity - thanks though! I hope the existing approach is good enough.

**Pull request closed without merging**
