### PR TITLE
use addons to include blackbox in all the places

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by vito** [comment]
At one point we couldn't do this because addons cannot come from a release that is then used in a deployment that then uses the same release (i.e. the rest of Concourse), but a different version. Is that still the case?

Might be able to just use the syslog boshrelease instead anyway, though.

**Comment by vito** [comment]
Oh wait, I think I see. This uses [addons in the manifest](http://bosh.io/docs/manifest-v2#addons) rather than the runtime config, which...probably avoids that issue?

Thanks! I'll pull this in and try it out.

**Comment by vito** [comment]
@drnic This seems to be ineffective. :/ I'm running BOSH v263, which should have this feature, and it seems to just be completely ignored. Does BOSH not allow you to use both runtime-config-based and deployment-local addons or something?

**Comment by cppforlife** [comment]
that addons section does not look right. should have jobs subsection and properties under those jobs.

**Comment by vito** [comment]
fixed: https://github.com/concourse/concourse-deployment/commit/610c208e20a89c67809927a5c6d1f3246d82cc8c - thanks

**Pull request merged**
