### PR TITLE
Add atc_basic_auth in variables

### PR DESCRIPTION
**Pull request by making**

### CODE REVIEW

**Comment by vito** [comment]
Similar questions/concerns as https://github.com/concourse/concourse-deployment/pull/27#issuecomment-351112091

**Comment by making** [comment]
I was thinking that specifying `-v atc_basic_auth.username=foo` can override this default variables but found it it not possible.
I'll separate this configuration.
Thanks!

**Comment by vito** [comment]
@making Maybe `-l`?

**Comment by making** [comment]
I made a mistake. Both `-v atc_basic_auth.username` and `-v atc_basic_auth.password` are required.

So, does providing a default `atc_basic_auth` that can be overridden by `-v atc_basic_auth.username` and `-v atc_basic_auth.password` make sense?

**Comment by vito** [comment]
Yeah sounds good.

**Pull request closed without merging**
